### ISSUE TITLE
请问/页面默认的title怎么改掉(Fu)，其它页面的没有问题

### ISSUE THREAD

**Issue by biluohc** [FuGangqiang/mdblog.rs#1]
base.tpl: 
主题里所有能看到的Fu都已经改了，或者在rust源码里面？
或者应该把它(网站名)放到config.toml?
另外还有favicon.ico和logo.png的路径。
```
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <link rel="icon" href="/media/static/img/favicon.ico">
  <link rel="stylesheet" href="/static/css/main.css">
  {% block css %}{% endblock css %}
  <title>{{ title }}</title>
</head>
<body>
```
生成的html
```
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <link rel="icon" href="/media/static/img/favicon.ico">
  <link rel="stylesheet" href="/static/css/main.css">
  
  <title>Fu</title>
</head>
<body>
```

**Comment by FuGangqiang** [comment]
所有的页面元素都是通过 theme 中的 template 控制的，
现在都是写死的，如果需要修改需要直接修改 `_themes/simple/templates/*.tpl` 这些文件里的对应项

我准备把那些可变的放到 `config.toml` 里面，不过现在能用，就懒得改了，
准备以后有空把这个功能加上

**Comment by biluohc** [comment]
我说了主题里所有我看到的Fu都改了，但是/页面的title还是Fu，就base.tpl里有三个，所以我怀疑是不是在rust源码里...

**Comment by FuGangqiang** [comment]
恩，是的，首页的标题在代码里面：
https://github.com/FuGangqiang/mdblog.rs/blob/926b55693bc9241c5ef108200e9fc161132ce129/src/lib.rs#L312
