### ISSUE TITLE
Add alternative title in post headers

### ISSUE THREAD

**Issue by alexmario74** [FuGangqiang/mdblog.rs#24]
How about adding an element on the header of the post to set the title.

Now mdblog get the post title from the file name, but this has a lot fo limits as the file names are bad with punctuation or with special characters.

And if for the title you want, the case is important, it can be missed on a file name (just in case of rename).

This new attribute should be optional, so mdblog will continue to use the file name as the blog title, but if the user set the title attribute, than this value is used to set the post title.

I think the change is pretty easy to make, and I can help if this is accepted.

**Comment by FuGangqiang** [comment]
sorry for late reply,

with the file name, add a title attribute. It's a bit redundant,
however, if you like this feature and implement it, I will merge it.

**Comment by alexmario74** [comment]
Thanks, I created a PR.

**Comment by FuGangqiang** [comment]
merged
