### ISSUE TITLE
`opts.insert(Options::ENABLE_FOOTNOTES);`  used twice

### ISSUE THREAD

**Issue by Sciroccogti** [FuGangqiang/mdblog.rs#29]
https://github.com/FuGangqiang/mdblog.rs/blob/fa06ebfd1076d12855e84f5abb17cc89517fd907/src/utils.rs#L33-L34

Seems to be a minor mistake here.

**Comment by FuGangqiang** [comment]
谢谢帮忙纠错

**Comment by FuGangqiang** [comment]
刚刚已修复这个问题
