### ISSUE TITLE
Themes should not have to contain logo.png

### ISSUE THREAD

**Issue by Sciroccogti** [FuGangqiang/mdblog.rs#30]
主题若不含 static/ 文件夹下的任何文件，就会报错

**Comment by FuGangqiang** [comment]
这个是默认行为，
初始化文件夹时的命令是 `mdblog init blog`，
这里会默认产生 static 目录

**Comment by Sciroccogti** [comment]
感觉更合理的话还是在 build 的时候，只要求存在 `static` 文件夹，不要求其中有固定的各个文件。

譬如我现在写的主题，就没有用到 `logo.png`，这时候却因为找不到这个文件而报错，其实感觉不太合适。

有可能的话，是否可以直接复制 `static` 文件夹？
或者仅复制其中某类文件，这样也便于主题添加其它的图片、文件等。

**Comment by FuGangqiang** [comment]
恩，有道理，
稍后会调整一下这个地方，
或者帮忙调整这个地方也可以
